### ISSUE TITLE
Find useful literature that research about block gas limit and block interval impact.

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#19]
# Task
## Detailed Description
We need to know if there is already literature that researched about the block gas limit and block interval impact over throughput. Specifically, if there is a formula or model to apply in our solution.
Update 17/12/19: As discussed in group the information found already confirms the influence of block gas limit and block time over throughput. However, the paper does not cover PoA with block interval. Further research is needed to find more related work.
## Associated story
Story: #14 Block gas limit and block interval optimal values
## Notes
The research should be documented here in a comment with the sources found. If possible, suggest a way of applying the solution.

**Comment by SantoshDhirwani** [comment]
The research is in progress and I will share a detailed outcome but sharing some links now, for @ulalaa14 so he can progress with his task. (As discussed in the call)

https://blog.coinfabrik.com/on-ethereum-performance-evaluation-using-poa/

https://fc16.ifca.ai/bitcoin/papers/CDE+16.pdf

https://bitcoin.stackexchange.com/questions/76203/how-are-block-interval-block-size-and-effective-throughput-related

**Comment by eltalkarim** [comment]
Thank you @santosh-dhirwani for your research. Can you please give us an explanation/presentation about the literature?
Not sure if this should be part of this issue or we need to create a new one. @boxrhcp 
Moreover, I think one paper is not enough can you please enrich it with more literature. Scientific papers or books. Also about optimizing the two param problem as Jörn said in the presentation.

**Comment by SantoshDhirwani** [comment]
Hi @eltalkarim. Thank you for your comment but the above comment is not my research. It is added as a document in the pull request that I created. You need to read that document first.

Here is the link: https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/pull/29

And it is apparent that I will present it to the team today.

**Comment by eltalkarim** [comment]
@SantoshDhirwani  I already saw the docx and what I mean is can you explain to us your findings when we meet? Moreover, I think one paper could be not enough maybe we can create others issue for that/

**Comment by SantoshDhirwani** [comment]
Okay great, then you should rather comment on the PR. Of course, I will and I have some more papers to share but I need more time to summarize them. I will share the papers along with their summaries as soon as I am done. Also, let's have a discussion today and agree on whether we still need further research.

**Comment by eltalkarim** [comment]
I did not comment on the PR because my comment is not related specifically to your contribution and more about different things including the definition of done for this task or creating on otherstasks. @SantoshDhirwani

**Comment by SantoshDhirwani** [comment]
Okay, cool

**Comment by SantoshDhirwani** [comment]
@eltalkarim Based on our discussion yesterday, here is the super short summary:-

Paper: Block Gas Limits vs. Transactional Throughput: A performance analysis of the Ubiq platform.

Contribution - 1 (Automation) : Not addressed
Contribution - 2 (Optimization) : Partially addressed

Why Partially Addressed? - It considers parameters based on Proof of Work consensus algorithm as well. For example, "difficulty".

**Comment by XhorxhinaT** [comment]
why is this still open? 

this paper references had a  couple more papers which could be interesting, but i could not find the pdf version online. Maybe our uni provides papers from their biblothek https://publik.tuwien.ac.at/files/publik_280601.pdf - An appropriate choice of block frequency and block size is crucial. Beacause of PoA it is observed a performance boost proportional to the increase in block size.
https://arxiv.org/pdf/1902.10244.pdf  explains how PoA works and Clique conditions to work.


https://blog.coinfabrik.com/on-ethereum-performance-evaluation-using-poa/#gas-limit states that the formel btw block size and block interval is one standard

**Comment by fayanpardo** [comment]
@XhorxhinaT nice related work! Actually the first paper shared is very useful for us. The related work section they wrote is exactly what we should have done for our presentation and we must do something along those lines for sure next time and for our final report. I also liked a lot how they explained their setup to test and all their procedures. Overall, I personally think this paper is a good example of how we should work and write our report.

They even found that geth and parity have performance differences and we already are fixing our solution to geth :/. But we must discuss about this in our next meeting.

**Comment by XhorxhinaT** [comment]
True the éxperiment setup, is also what drove me in. But since I wanted to discuss the parameters beforehand with you, I didn't work fully with methodology section yet.

**Comment by XhorxhinaT** [comment]
Gas Limit
Ethereum platform prevents transaction spamming and rewards block miners by charging a gas fee on transactions. Each block contains a maximum amount of gas that can be collected from transactions, defining a maximum block size. That gas limit could be set as a configuration parameter. In the long term, the block gas limit approaches a target gas limit set also as a configuration parameter (it can also be changed at runtime if needed). The theoretical maximum transactions per second (TPS) can be calculated using the following equation:

https://blog.coinfabrik.com/on-ethereum-performance-evaluation-using-poa/#block-time

where GasLimit is the Block gas limit, TxGas is the gas needed to compute the simplest transaction and Block time is the blockchain block time.





https://forum.ethereum.org/discussion/1757/maximum-block-size : The default gas limit per block on the testnet is 1B. On the livenet we tentatively are looking at 1M, again this is likely to change after our stress tests.  Note that each call to the contract to the caller cost an amount of Ether defined by (gas sent to contract)*(price of gas as defined by caller) so sending 10,000 trx per block could end up quite a pricey endeavour.





https://ethereum.stackexchange.com/questions/1106/is-there-a-limit-for-transaction-size/1110#1110  - strength of the Etherem network: it does scale.
That does not mean that there are no limits. There is the block gas limit of currently 3,141,592 gas which can be spent maximum per block.
That means, in theory you could create a single transaction which consumes all the gas of a single block.


https://ethgasstation.info/blog/ethereum-block-size/
https://medium.com/@piyopiyo/how-to-get-ethereum-block-gas-limit-eba2c8f32ce




Block size limit
There is no maximum Ethereum block size. While Bitcoin has a fixed block size of 1 mb, Ethereum’s block size varies.

What determines Ethereum block size?
Instead of a fixed limit, Ethereum block size is bound by how many units of gas can be spent per block. This limit is known as the block gas limit (sometimes confused with transaction gas limit). At the time of writing this, miners are currently accepting blocks with an average block gas limit of around 10,000,000 gas. Currently, the average Ethereum block size is anywhere between 20 to 30 kb in size.




These are multiple factors that would come into play. I can't bet 1000 TPS, but definitely much higher throughput than average. I have achieved transactions in three digits by playing with these factors in a private network.
1.	Consensus/ Engine used- PoA will always beat PoW in your case.
2.	Number of Nodes the lower the better! The more the number of nodes you have, the more difficulty in reaching consensus (probabilistically speaking), but you also lose resilience in the network. What if the only node you have just crashed or someone turns it off? Based on your infrastructure 2-3 could be optimum.
3.	Node/ server specs Depends on the use case and volume. You mentioned transfer event based off of ERC20, but volume matters too (only in terms of storage and not RAM actually). Anything with 2GB RAM on a linux machine should be fine. I used t3.medium on AWS (with a storage of 40GB, but storage depends on your volume).








Block Size The higher the block size, the more transactions you can pack in a single block. Technically, you would increase the block size by increasing the gas limit in the configuration file.
Block Time The lower the block time, the quicker the blocks will get mined. But if it is too low and your network has many nodes, then there could increse chances of stale transactions. (averagly min used 5sec, in PoA aura 1sec as well)
https://ethereum.stackexchange.com/questions/37985/what-is-the-safest-minimum-block-time-to-use-without-having-any-problem-on-proof






To increase the TPS you need to do this:
1.	Set Block Limit to its maximum. Currently miners are voting on Block Limit, so the theoretical speed of 800 TPS on Ethereum Main Net can't be reached because of that.
2.	Use better hardware on all nodes that are mining. This includes network and the machine itself. So you can theoretically achieve 2,000 or more TPS if you use twice as fast hardware. Put the SSD disks in RAID 0 and get the doble in speed increase.


The bottleneck in Ethereum is the State Trie and the EVM. To speed up State Trie access get faster SSDs and large amount of RAM to cache disk blocks. To speed up the EVM get faster RAM and and CPUs.
If you won't create many accounts and many contracts on your private net, it will be very fast, much faster than 1,000 TPS. Ethereum is slow because it has around 40 million accounts, and its State Trie has around 300 milion nodes. Getting the balance of 1 account takes 10 to 20 milliseconds because it has to do dozens of lookups to disk at random location. If you don't have that many accounts, just increasing RAM size of your nodes will make Linux cache all the blocks and processing time will be very fast.
 



We don’t know if its non linear or linear. 

There are several possibilities for the nature of the constraint set, also known as the feasible set or feasible region.
An infeasible problem is one for which no set of values for the choice variables satisfies all the constraints. That is, the constraints are mutually contradictory, and no solution exists; the feasible set is the empty set.
A feasible problem is one for which there exists at least one set of values for the choice variables satisfying all the constraints.

We suppose that the block size can get get as big as we want and block period is not limiter either
An unbounded problem is a feasible problem for which the objective function can be made to be better than any given finite value. Thus there is no optimal solution, because there is always a feasible solution that gives a better objective function value than does any given proposed solution.

**Comment by XhorxhinaT** [comment]
https://blog.coinfabrik.com/on-ethereum-performance-evaluation-using-poa/#block-time Lower block times were found to be strongly related to higher amount of lost blocks per valid blocks, which leads to a bad performance of the blockchain. It would be better if when one of these sealers is selected as a leader, it had higher chances of generating a valid block. For this to take place we recommend not to use lower block times. On the other hand, using 30 seconds block times some delays problems were also reported. Based on these analysis, we propose to use block times between 10 and 15 seconds, to keep a high TPS. Block times between 15 and 20 seconds are also expected to lead to a good performance, but were not tested in this analysis.


https://publik.tuwien.ac.at/files/publik_280601.pdf .   For PoA, we
used block periods of 2, 4, 8, 12, and 15 seconds. The experiments confirmed:
throughput decreases and latency increases linearly with increasing block period.



My conclusions: we have not a fixed interval of block size and block time, but the connection is evident: Max Thorughout= max block size( max gas limit target) and min block time
Very probable non linear, since there is no constant connection with the proportion of these parameters.
