### ISSUE TITLE
Create Workload deployment script

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#24]
# Task
## Detailed Description
We need to create a workload deployment script. This deployment script will use the caliper image and will build the same number of containers as number of nodes of the SUT. When deployed, each container will benchmark one node and generate results.
## Associated story
Story: #22  Workload deployment
## Notes
We need to discuss how are we going to gather the experiment result from each container

**Comment by SantoshDhirwani** [comment]
@boxrhcp This needs to be broken down into 3 sub-tasks:

- Script to build the same number of containers as the number of nodes and to use the caliper image to benchmark them.

- Script to gather results of caliper containers.

- Validate if we can hit several nodes from the same caliper image rather than creating multiple caliper instances inside the image.
